 /* Add to the MOOCexperience! Add to any of the feedlots below */
 
 /* These are the really big heifers we might hope to be,
	if only we bad an IPO */
 var big_cows = [
 	'Coursera',
	'FutureLearn',
	'edX',
	'Khan Academy',
	'LinkedIn Learning',
	'Udacity',
	'Udemy'
];

 /*  Who might blog about MOOCs? Leave out so called 'Thought Leaders',
	pee you */
 var big_bloggers = [
 	'Martin Weller',
	'Stephen Downes',
	'Michael Feldstein',
	'Phil Hill',
	'Audrey Watters',
	'Brian Lamb',
	'Anne-Marie Scott',
	'Maha Bali',
	'Bon Stewart',
	'Laura Gibbs',
	'Lisa Lane',
	'Heather Ross',
	'Tannis Morgan'
 ];

 /* Fun names for the buttons */
 var little_cows = [
 	'Make Me Another',
 	'More MOOCs, please!',
	'MOOC it Again',
	'Gimme More',
	'One More MOOC',
	'Mooooooooooc!'
];
 
 // arrays of subjects- if a single quote or apostrophe needed, enter as \'
let subject = [	
	'Advanced Design of',
	'Introduction to',
	'A First Experience in',
	'Applications of',
	'Complex Concepts of',
	'Introductory',
	'Topics In',
	'Equality of',
	'Applied',
	'Principles of',
	'Literature of',
	'Research in',
	'Special Topics in',
	'Critical Issues Facing',
	'Reflections on',
	'Guiding principles of',
	'An inquiry into',
	'Definitive proofs in',
	'Basic Building Blocks of',
	'Research Capstone In',
	'Quantitative Methods In',
	'Ethnicity In',
	'Misspellings Embedded in',
	'Antagnostic Syllables as they relate to',
	'Beyond',
	'Past Beyond',
	'A Funny Thing Happened in the',
	'From ',
	'To',
	'21st Century',
	'Explorations of',
	'An Historical Analysis of',
	'Everything You Ever Wanted To Know About',
	'Deconstructing The Spaces Between',
	'Mooving MOOC Moments in ',
	"An Idiot's Guide to",
	'An Analytical Approach to',
	'Compendium of',
	'An Moralistic Study of ',
	'Guidlines for',
	'The Fourth Law of Thermodynamics in the',
	'A Critical approach to',
	'A transvarient lens approach to ',
	'Rainbow Transhumanism and',
	'Inner Workings of',
	'The current state of ',
	'A revisionist history of',
	'An Epistomology of',
	'Qualitative Analysis in',
	'Transpatial Relationships of',
	'Transmedua Storytelling and',
	'Visualization of ',
	'Data Tranformations and',
	'Protosymbolism and',
	'Neocolonialism of',
	'Barefoot Victims of',
	'Undocumented Origins of',
	'Repressed Associations with',
	'Freshman Survey of',
	'Social Origins of',
	'Epic Failures in',
	'Synchronized Assessment of',
	'Visualizing',
	'Interdisciplinary Monologues on',
	'Cultural Disregard for',
	'Who is',
	'Mysterious Degredation of',
	'Invasive Species of',
	'Politicians Who Consume',
	'Historical Reconstruction of',
	'Victorian Explorations in',
	'Chemical Reactions to',
	'Metaphorical Hallucinations of',
	'Theoretical Underpinnings of',
	'Contemporary Delusions in',
	'Mediated Approaches to',
	'Regurgitating',
	'Paranoid Ramblings in',
	'Curative Powers of',
	'How to Eat',
	'Titration of',
	'Synergy in',
	'Flatulant Ramblings Embodying the',
	'101 Reasons Explaining',
	'Why You Need',
	'Radical Dissection of',
	'Just When You Thought You Understood',
	'What every Capitalist Running Dog Needs to Know about',
	'How to Make',
	'Everything You Feared About',
	'Building a More',
	'Why We Are a',
	'Motörhead and',
	'A Transrational Dialogic Approach to',
	'A Quantam Approach to',
	'Ripping the Truth Out of',
	'An Examination of',
	'Survey of',
	'An Exploration of'];
  
// arrays of adjectives- if a single quote or apostrophe needed, enter as \'

let adjectives = [	'Critical',
	'Revolutionary',
	'Transformative',
	'Multimodal',
	'Psychological',
	'Minor',
	'Major',
	'Historical',
	'Interntional',
	'Meta-Physical',
	'Postmodern',
	'Ancient',
	'Post Modern',
	'Self-Actualizating',
	'Barnyard',
	'Anthropomorphic',
	'Sensory',
	'Canadian',
	'Ecological',
	'Kafkaesque',
	'Newtonian ',
	'Bilingual ',
	'Dimensional ',
	'Reformist',
	'Contemporary',
	'Paleolithic',
	'Progressive',
	'Abnormal',
	'Disruptive',
	'Unintelligible',
	'Keg-Fueled',
	'Irrepressible',
	'Stretchy',
	'Really Nice',
	'Pre-Cambrian',
	'Utopian',
	'Dystopian',
	'Pre-Columbian',
	'Bizarre ',
	'Global',
	'Marxist',
	'Darwinian',
	'Disinterested',
	'Engendered',
	'Anti-Establishment',
	'Subparticle',
	'Free-form',
	'Altruistic',
	'Antiquated',
	'Future Oriented',
	'Eastern',
	'Western',
	'Cannablisitic',
	'Inbred',
	'Open',
	'Post Post Modern',
	'Degenerative',
	'Introspeculative',
	'Catastrophic',
	'Manufactured',
	'Marginalized',
	'Opportunistic',
	'Paleolithic',
	'Unrehearsed',
	'Zuckerbergian',
	'Your',
	'Flat World',
	'Blatant',
	'Shiny',
	'Caramel',
	'Recreational',
	'Visceral',
	'Celebrated',
	'Rusty',
	'Retractable',
	'Everymans',
	'Conceptualized',
	'Copacetic',
	'Supercalifragilisticexpialidocious',
	'Meretricious',
	'Avuncular',
	'Boisterous',
	'Mellifluous',
	'Itchy',
	'Nutritous',
	'Perennial',
	'Old-Style',
	'Unreconstructed',
	'Beautiful',
	'Gluten-Free',
	'Googley',
	'Fearless',
	'Autonomous',
	'Ethereal',
	'Fractal',
	'Beligerent',
	'Autonomous',
	'American',
	'Experimental'];
	
	
// arrays of topics- if a single quote or apostrophe needed, enter as \'
let topics = [
	'Connectivism',
	'Learning Theory',
	'Cubism',
	'Physics',
	'Bioscience',
	'Algorithms',
	'Artificial Intelligence',
	'Suburban Sociology',
	'American Studies',
	'Aquatics',
	'Culinary Arts',
	'Elbonian Dance',
	'Microeconomics',
	'Viking Architecture',
	'Population Dynamics',
	'Community Health',
	'MongoDB',
	'Gentics',
	'Evolution',
	'Gamification',
	'Mathematical Thinking',
	'Cartooning',
	'Jim Groom ',
	'Luxury Resort Amenities',
	'Connectivism 2.0+',
	'Horror & Mythology',
	'Pre-Roman Folklore',
	'Multiculturalism',
	'MOOCs',
	'Constructionary',
	'Universities',
	'Interspeciality',
	'Pencil Shaving',
	'Mathamagical Theology',
	'Peruvian Folklore',
	'Critical Thinking',
	'Entrepreneurship',
	'Sanskrit Words',
	'Arthouse Cinema',
	'Archaeology',
	'Phenotype',
	'Phenomenography',
	'Coprology',
	'Walking Gaits',
	'Posthumanism',
	'The 99%',
	'Food Preparation',
	'Gerontology',
	'Business Ethics',
	'Intramural Sports',
	'Phrenology',
	'Cosmology',
	'Mineralogy',
	'Innovation',
	'Education',
	'Invertebrates',
	'Locavores',
	'Table Dancing',
	'Paperweights',
	'Ceiling Tiles',
	'Cubicle Romance',
	'Curling',
	'Pants',
	'Basket weaving',
	'Ostriches',
	'daddy?',
	'Carpet Beetles',
	'Sports',
	'Boxers',
	'Briefs',
	'Intentions',
	'Refugees',
	'Emissions',
	'Design Thinking',
	'Landscape',
	'Venture Capitalists',
	'Slavoj Žižek',
	'Metallurgy',
	'Metamorphisms',
	'Heterodoxy',
	'Grateful Dead',
	'Guitar-Stringing',
	'Bunions',
	'Inquiry',
	'Motivations',
	'Transportation Models',
	'Marxism',
	'Things with your Hands',
	'Gertude Stein',
	'Linkbait',
	'Stuxnet',
	'Doomsday Preppers',
	'Anthropophagy',
	'Super Mario',
	'Flying Squirrels',
	'Detectives',
	'Phenylikatonics',
	'Paint Drying'];
	
// arrays of stuff after the colon- if a single quote or apostrophe needed, enter as \'
let postcolon = [
	'How to Make it Fail',
	'Gender Dynamics',
	'Methods and Best Practices',
	'Performance as Meaning',
	'A Collage Seen In American Dance',
	'An Aesthetic Genre',
	'Critical Thinking and Relationships',
	'A Process Approach',
	'The Downes Principle',
	'A Figure Of New Culture',
	'In The American Landscape',
	'The Greening Theorem At Work',
	'Myth & Reality',
	'A Presentation Explored In Estonian Art',
	'Liberated Polytheistic Mythology',
	'Paganism In The Postmodern Era',
	'Ideas In Conflict',
	'In Modern Architecture',
	'Our shared sacrifice ',
	'How Zack Morris continues to change our world',
	'The systematic inversion of traditional metaphysical relationships between identity and difference',
	'A narrative exploration of characters in Bob Dylans songs between 1973-1980',
	'Meditations on coastal foliage ',
	'The novels of Bendigo Juarez',
	'As told through the rhythmic contortionism of the American southwest',
	'The Science and Beyond',
	'The Way Forward',
	'A Paradigm Shift',
	'Critical Issues Facing The 21st Century',
	'From Oberholser To Mahoney',
	'As Interpreted In Inner City Female Paintings',
	'An Interdisciplinary Study',
	'An Odyssey Of Discovery',
	'Work, Struggle, And Race In The Real World',
	'Around the World, in 80 Networks',
	'The Coming Collapse of Global Capital',
	'Experienced in T-shirt Design',
	'Naked, Exposed,and Open',
	'In The Writings of the Blessed John Henry Newman',
	'as Heard on #ds106radio Last Night at 3 am in the EST',
	'An irresistible journey',
	'The dawn of learnism',
	'The moocification of everything',
	'In the Context of Mid 21st Century MOOC Abolishment',
	'Liberating your Inner Child',
	'An Operational Perspective',
	'A Holistic Approach',
	'Defying Newtonian Physics',
	'Creating an Intelligent-Sounding Yet Useless Speech',
	'The Glorious world of the genius of 35mm film',
	'Through the Lens of Darwin',
	'The Feminist Perspective',
	'The final course',
	'A poststructuralist perspective',
	'Educating the World',
	'Why We Should Care',
	'Whats Not to Like?',
	'Thats What She Said',
	'I Was Here First',
	'Lean In',
	'Move Your Own Cheese',
	'In Bed',
	'Caffeine is not a drug',
	'The Best Course EVAR',
	'Now What?',
	'A course in geneaology',
	'Because I Said So',
	'Not your grandmothers MOOC',
	'A technosocial analysis',
	'Not My Problem',
	'Srsly?',
	'I Meant to Do That',
	'It Takes a Village',
	'Fair Enough',
	'Call Me, Maybe?',
	'Never Say Never',
	'I am Telling You Why',
	'Neil Postman Zombie Studies',
	'Another One Bites the Dust',
	'Science as a Performative Gender',
	'Put Your Safety Goggles on First, said Ayn Rand',
	'What a Long Strange Trip It Has Been',
	'In the Technical Time',
	'That You Should Know',
	'Explained and Exposed',
	'A Tabloid-Style Exposé',
	'Why You Need an Oscillation Overthruster',
	'Or how to eat the rich without throwing up',
	'Stuff You Won\'t Learn Here',
	'The Sequel',
	'The Rise of the Machines',
	'Don\'t Say I Didn\'t Warn You',
	'Opening the Kimono',
	'An Epic Win',
	'Why The House Always Wins',
	'A Postpartum Perspective',
	'Ain\'t They Cute',
	'Friends or Lovers?',
	'In the Canadian Landscape'
];
